name: myenv  # 环境名称
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.4
  - torch
  - numpy=1.22.3
  - pandas=1.4.4
  - ipython==8.10.0
  - jupyter==1.0.0
  - tqdm==4.66.1
  - scipy==1.7.3
  - scikit-learn==1.1.3
  - matplotlib
  - pickle
  - yaml
  - pip
